#!/usr/bin/env bash
# PreToolUse hook: block writes to sensitive, generated, or agent-owned paths.
#
# Trigger: PreToolUse with matcher "Edit|Write|MultiEdit".
# Behavior: read tool_input.file_path, exit 2 if it matches a pattern below.
# Exit 0 otherwise.

set -u

# shellcheck source=./_parse.sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/_parse.sh"

HOOK_INPUT="$(cat)"
FILE_PATH="$(hook_extract "$HOOK_INPUT" tool_input.file_path)"

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Normalize separators so the glob matches work on Git Bash (Windows).
NORMALIZED="${FILE_PATH//\\/\/}"

block() {
  local reason="$1"
  cat >&2 <<EOF
Blocked by .claude/hooks/block-sensitive-paths.sh

Reason: $reason

Path: $FILE_PATH

If this file genuinely needs editing, ask the user to do it manually.
EOF
  exit 2
}

case "$NORMALIZED" in
  */.env.example|.env.example|*/.env.*.example|.env.*.example)
    # Committed template — documents variable names with placeholder values, no
    # real secrets. Allow edits (must precede the .env arm below).
    exit 0
    ;;
  */.env|*/.env.*|.env|.env.*)
    block ".env files contain secrets."
    ;;
  */config/credentials.*|config/credentials.*)
    block "credentials files contain secrets."
    ;;
  */secrets/*|secrets/*)
    block "secrets/ contains secrets."
    ;;
  */.npmrc|.npmrc)
    block ".npmrc can carry a registry auth token. dogear publishes to npm — never hand-edit this."
    ;;
  */node_modules/*)
    block "node_modules/ is installed, not authored. Change the dependency and ask the user to reinstall."
    ;;
  */dist/*)
    block "dist/ is build output. Edit the source and rebuild."
    ;;
  */.dogear/queue.json|.dogear/queue.json)
    # dogear eats its own dog food: the queue is mutated through the MCP
    # resolve/prune tools, never by hand. A model surgically editing JSON is a
    # reliable way to produce malformed JSON — which is the exact failure mode
    # dogear_resolve exists to prevent.
    block "The dogear queue is agent-owned state. Use the dogear_resolve / dogear_prune MCP tools (or 'dogear prune'), never a hand edit."
    ;;
  */package-lock.json|package-lock.json)
    block "package-lock.json is generated by npm. Change package.json and ask the user to run the install."
    ;;
esac

exit 0
